---
- name: Instalar e configurar TeamViewer Host
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    teamviewer_assignment_id: "0001CoABChC1doBwE6ER8IVwcOHTKq14EigIACAAAgAJAM3Fqx3YiSeapvhzY1fZ8C0OXCwtZ8U5tipZMciFfn2AGkCxyzcacCO8UWFdx9o9IUS-gm_1hFpKpbQu7dAn5AQyXkQ2JP8BzlG9TP3U_d60grO7ngCTd93lRX8CuELqctwvIAEQocTBxAM="
    teamviewer_deb_path: /tmp/teamviewer-host.deb
    teamviewer_wait_time: 20

  tasks:
    - name: Atualizar cache do APT
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Instalar dependências necessárias
      ansible.builtin.apt:
        name:
          - wget
          - ca-certificates
        state: present

    - name: Verificar se TeamViewer já está instalado
      ansible.builtin.command:
        cmd: dpkg -l teamviewer-host
      register: teamviewer_installed
      failed_when: false
      changed_when: false

    - name: Baixar TeamViewer Host
      ansible.builtin.get_url:
        url: https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
        dest: "{{ teamviewer_deb_path }}"
        mode: '0644'
        timeout: 60
      when: teamviewer_installed.rc != 0

    - name: Instalar TeamViewer Host
      ansible.builtin.apt:
        deb: "{{ teamviewer_deb_path }}"
        state: present
      when: teamviewer_installed.rc != 0
      register: teamviewer_installation

    - name: Corrigir permissões do diretório de configuração
      ansible.builtin.file:
        path: /opt/teamviewer/config
        state: directory
        mode: '0755'
        recurse: yes

    - name: Corrigir permissões do arquivo global.conf
      ansible.builtin.file:
        path: /opt/teamviewer/config/global.conf
        state: touch
        mode: '0644'
      ignore_errors: yes

    - name: Parar daemon do TeamViewer (se estiver rodando)
      ansible.builtin.command:
        cmd: teamviewer --daemon stop
      register: stop_daemon
      failed_when: false
      changed_when: stop_daemon.rc == 0

    - name: Aguardar 3 segundos após stop
      ansible.builtin.pause:
        seconds: 3

    - name: Habilitar daemon do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --daemon enable
      register: enable_daemon
      changed_when: "'enabled' in enable_daemon.stdout or enable_daemon.rc == 0"
      failed_when: enable_daemon.rc != 0 and 'already enabled' not in enable_daemon.stderr

    - name: Iniciar daemon do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --daemon start
      register: start_daemon
      changed_when: "'started' in start_daemon.stdout or start_daemon.rc == 0"
      failed_when: start_daemon.rc != 0 and 'already running' not in start_daemon.stderr

    - name: Aguardar daemon inicializar completamente
      ansible.builtin.pause:
        seconds: 5

    - name: Reiniciar daemon do TeamViewer para aplicar permissões
      ansible.builtin.command:
        cmd: teamviewer --daemon restart
      register: restart_daemon
      changed_when: restart_daemon.rc == 0

    - name: Aguardar daemon reiniciar
      ansible.builtin.pause:
        seconds: 8

    - name: Aceitar licença do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer license accept
      register: license_accept
      changed_when: license_accept.rc == 0 and 'already' not in license_accept.stdout
      failed_when: false

    - name: Verificar aceitação da licença
      ansible.builtin.debug:
        msg: "{{ 'Licença já estava aceita' if 'already' in license_accept.stdout else 'Licença aceita com sucesso' }}"

    - name: Aguardar estabilização dos serviços
      ansible.builtin.pause:
        seconds: "{{ teamviewer_wait_time }}"

    - name: Verificar se TeamViewer ID foi gerado
      ansible.builtin.shell:
        cmd: teamviewer --info | grep "TeamViewer ID:" | awk '{print $3}'
      register: teamviewer_id_check
      changed_when: false
      failed_when: false

    - name: Mostrar TeamViewer ID
      ansible.builtin.debug:
        msg: "TeamViewer ID: {{ teamviewer_id_check.stdout }}"
      when: teamviewer_id_check.stdout != ""

    - name: Verificar se daemon está rodando corretamente
      ansible.builtin.command:
        cmd: teamviewer --info
      register: teamviewer_info_pre
      failed_when: false
      changed_when: false

    - name: Mostrar status pré-assignment
      ansible.builtin.debug:
        msg: "{{ teamviewer_info_pre.stdout_lines }}"
      when: teamviewer_info_pre.rc == 0

    - name: Atribuir dispositivo à conta TeamViewer
      ansible.builtin.shell:
        cmd: 'teamviewer assignment --id {{ teamviewer_assignment_id }} --device-alias="$(hostname) - Linux"'
      register: assignment_result
      retries: 3
      delay: 10
      until: assignment_result.rc == 0
      failed_when: false
      changed_when: assignment_result.rc == 0

    - name: Mostrar resultado da atribuição
      ansible.builtin.debug:
        msg: |
          ========================================
          Resultado do assignment:
          ========================================
          Código de retorno: {{ assignment_result.rc }}
          {% if assignment_result.rc == 0 %}
          ✅ Assignment realizado com sucesso!
          {% else %}
          ⚠️  Assignment falhou ou já estava atribuído
          {% endif %}
          
          Saída: {{ assignment_result.stdout }}
          {% if assignment_result.stderr %}
          Erros: {{ assignment_result.stderr }}
          {% endif %}
          ========================================

    - name: Verificar informações finais do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --info
      register: teamviewer_info_final
      changed_when: false

    - name: Mostrar informações finais do TeamViewer
      ansible.builtin.debug:
        msg: "{{ teamviewer_info_final.stdout_lines }}"

    - name: Limpar arquivo de instalação
      ansible.builtin.file:
        path: "{{ teamviewer_deb_path }}"
        state: absent

    - name: Mensagem final
      ansible.builtin.debug:
        msg: |
          ========================================
          Instalação do TeamViewer concluída!
          Considere reiniciar o sistema para garantir estabilidade.
          Comando: sudo reboot
          ========================================
          