---
- name: Instalar e configurar TeamViewer Host (igual ao processo manual)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    teamviewer_assignment_id: "0001CoABChC1doBwE6ER8IVwcOHTKq14EigIACAAAgAJAM3Fqx3YiSeapvhzY1fZ8C0OXCwtZ8U5tipZMciFfn2AGkCxyzcacCO8UWFdx9o9IUS-gm_1hFpKpbQu7dAn5AQyXkQ2JP8BzlG9TP3U_d60grO7ngCTd93lRX8CuELqctwvIAEQocTBxAM="

  tasks:
    - name: Mudar para diretório /tmp
      ansible.builtin.shell:
        cmd: cd /tmp
        executable: /bin/bash
      changed_when: false

    - name: Baixar TeamViewer (igual ao comando wget)
      ansible.builtin.shell:
        cmd: wget -O teamviewer-host.deb https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
        executable: /bin/bash
      args:
        chdir: /tmp

    - name: Instalar TeamViewer (igual ao comando apt)
      ansible.builtin.apt:
        deb: /tmp/teamviewer-host.deb
        state: present

    - name: Habilitar daemon do TeamViewer
      ansible.builtin.shell:
        cmd: teamviewer --daemon enable
        executable: /bin/bash
      register: enable_daemon
      changed_when: "'already enabled' not in enable_daemon.stdout"

    - name: Iniciar daemon do TeamViewer
      ansible.builtin.shell:
        cmd: teamviewer --daemon start
        executable: /bin/bash
      register: start_daemon
      changed_when: "'already running' not in start_daemon.stdout"
      ignore_errors: yes

    - name: Aceitar licença do TeamViewer
      ansible.builtin.shell:
        cmd: teamviewer license accept
        executable: /bin/bash
      register: license_accept
      changed_when: "'already accepted' not in license_accept.stdout"

    - name: Aguardar 5 segundos para serviços estabilizarem
      ansible.builtin.pause:
        seconds: 5

    - name: Atribuir dispositivo à conta TeamViewer (comando exato)
      ansible.builtin.shell:
        cmd: teamviewer assignment --id {{ teamviewer_assignment_id }} --device-alias="{{ ansible_hostname }}"
        executable: /bin/bash
      register: assignment_result
      async: 45
      poll: 5

    - name: Mostrar resultado da atribuição
      ansible.builtin.debug:
        msg: "Resultado do assignment: {{ assignment_result.stdout }}"

    - name: Verificar status do TeamViewer
      ansible.builtin.shell:
        cmd: teamviewer --info
        executable: /bin/bash
      register: teamviewer_info

    - name: Mostrar informações do TeamViewer
      ansible.builtin.debug:
        msg: "TeamViewer Info: {{ teamviewer_info.stdout }}"

    - name: Limpar arquivo de instalação
      ansible.builtin.file:
        path: /tmp/teamviewer-host.deb
        state: absent