---
- name: Instalar e configurar TeamViewer Host (processo manual corrigido)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    teamviewer_assignment_id: "0001CoABChC1doBwE6ER8IVwcOHTKq14EigIACAAAgAJAM3Fqx3YiSeapvhzY1fZ8C0OXCwtZ8U5tipZMciFfn2AGkCxyzcacCO8UWFdx9o9IUS-gm_1hFpKpbQu7dAn5AQyXkQ2JP8BzlG9TP3U_d60grO7ngCTd93lRX8CuELqctwvIAEQocTBxAM="

  tasks:
    - name: Baixar TeamViewer para /tmp
      ansible.builtin.get_url:
        url: https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
        dest: /tmp/teamviewer-host.deb
        mode: '0644'
        timeout: 30

    - name: Instalar TeamViewer
      ansible.builtin.apt:
        deb: /tmp/teamviewer-host.deb
        state: present

    - name: Habilitar daemon do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --daemon enable
      register: enable_daemon
      changed_when: "'already enabled' not in enable_daemon.stdout"

    - name: Iniciar daemon do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --daemon start
      register: start_daemon
      changed_when: "'already running' not in start_daemon.stdout"
      ignore_errors: yes

    - name: Aceitar licença do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer license accept
      register: license_accept
      changed_when: "'already accepted' not in license_accept.stdout"

    - name: Aguardar 10 segundos para serviços estabilizarem
      ansible.builtin.pause:
        seconds: 10

    - name: Atribuir dispositivo à conta TeamViewer
      ansible.builtin.command:
        cmd: "teamviewer assignment --id {{ teamviewer_assignment_id }} --device-alias '{{ ansible_hostname }}'"
      register: assignment_result
      async: 60
      poll: 10

    - name: Mostrar resultado da atribuição
      ansible.builtin.debug:
        msg: "Resultado do assignment: {{ assignment_result.stdout }}"

    - name: Verificar status do TeamViewer
      ansible.builtin.command:
        cmd: teamviewer --info
      register: teamviewer_info

    - name: Mostrar informações do TeamViewer
      ansible.builtin.debug:
        msg: "TeamViewer Info: {{ teamviewer_info.stdout }}"

    - name: Limpar arquivo de instalação
      ansible.builtin.file:
        path: /tmp/teamviewer-host.deb
        state: absent