---
- name: Instalar e configurar TeamViewer Host de forma não interativa
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    teamviewer_version: "teamviewer-host_amd64.deb"
    teamviewer_url: "https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb"
    teamviewer_assignment_id: "0001CoABChC1doBwE6ER8IVwcOHTKq14EigIACAAAgAJAM3Fqx3YiSeapvhzY1fZ8C0OXCwtZ8U5tipZMciFfn2AGkCxyzcacCO8UWFdx9o9IUS-gm_1hFpKpbQu7dAn5AQyXkQ2JP8BzlG9TP3U_d60grO7ngCTd93lRX8CuELqctwvIAEQocTBxAM="
  
  tasks:
    - name: Baixar TeamViewer Host
      ansible.builtin.get_url:
        url: "{{ teamviewer_url }}"
        dest: "/tmp/{{ teamviewer_version }}"
        mode: '0644'

    - name: Configurar variáveis de ambiente para instalação não interativa
      ansible.builtin.shell:
        cmd: |
          export DEBIAN_FRONTEND=noninteractive
          export TEAMVIEWER_ACCEPT_EULA=yes
          dpkg -i /tmp/{{ teamviewer_version }} || apt-get install -f -y
        executable: /bin/bash

    - name: Forçar aceitação de EULA via comando
      ansible.builtin.shell:
        cmd: |
          echo -e "1\n1" | teamviewer setup
        executable: /bin/bash
      ignore_errors: yes

    - name: Configurar aceitação via arquivo
      ansible.builtin.blockinfile:
        path: /etc/teamviewer/global.conf
        block: |
          EulaAccepted = 1
          DataEulaAccepted = 1
          ClientAutoStart = 1
        create: yes
        mode: '0644'

    - name: Reiniciar serviço TeamViewer
      ansible.builtin.systemd:
        name: teamviewerd
        state: restarted
        enabled: yes

    - name: Aguardar estabilização do serviço
      ansible.builtin.pause:
        seconds: 10

    - name: Executar assignment de forma não interativa
      ansible.builtin.shell:
        cmd: |
          teamviewer assignment --id {{ teamviewer_assignment_id }} --device-alias="{{ ansible_hostname }}"
        executable: /bin/bash
      register: assignment
      retries: 5
      delay: 10

    - name: Limpar arquivo de instalação
      ansible.builtin.file:
        path: "/tmp/{{ teamviewer_version }}"
        state: absent

    - name: Verificar instalação
      ansible.builtin.command:
        cmd: teamviewer --version
      register: version_check
      changed_when: false

    - name: Mostrar resultado final
      ansible.builtin.debug:
        msg: |
          TeamViewer instalado: {{ version_check.stdout }}
          Assignment: {{ assignment.stdout }}